#!/bin/sh
 
if [ "$*" = "clean" ] ; then
    make -f nbproject/Makefile-ARM.mk QMAKE= SUBPROJECTS= .clean-conf	
	make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .clean-conf
	make -f nbproject/Makefile-ARM_Hi3535.mk QMAKE= SUBPROJECTS= .clean-conf
	make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .clean-conf
	make -f Makefile-exe clean
elif [ "$*" = "arm" ] ; then
    make -f nbproject/Makefile-ARM.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "3535" ] ; then
    make -f nbproject/Makefile-ARM_Hi3535.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "x64" ] ; then
    make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "exe" ] ; then
    make -f Makefile-exe
else 
	make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
fi
